hw3/config/routes.rb
Hw3::Application.routes.draw do
  resources :people

end

hw3/app/models/person.rb
class Person < ActiveRecord::Base
	validates :Name, :presence => true
	validates :Affiliation, :presence => true
	validates :Email_Address, :presence => true
	validates_format_of :Email_Address, :with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i, :message => 'entered is invalid'
end

hw3/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

hw3/app/controllers/people_controller.rb
class PeopleController < ApplicationController
  # GET /people
  # GET /people.xml
  def index
    @people = Person.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @people }
    end
  end

  # GET /people/1
  # GET /people/1.xml
  def show
    @person = Person.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @person }
    end
  end

  # GET /people/new
  # GET /people/new.xml
  def new
    @person = Person.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @person }
    end
  end

  # GET /people/1/edit
  def edit
    @person = Person.find(params[:id])
  end

  # POST /people
  # POST /people.xml
  def create
    @person = Person.new(params[:person])

    respond_to do |format|
      if @person.save
        format.html { redirect_to(@person, :notice => 'You have successfully registered!') }
        format.xml  { render :xml => @person, :status => :created, :location => @person }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @person.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /people/1
  # PUT /people/1.xml
  def update
    @person = Person.find(params[:id])

    respond_to do |format|
      if @person.update_attributes(params[:person])
        format.html { redirect_to(@person, :notice => 'You have successfully registered!') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @person.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.xml
  def destroy
    @person = Person.find(params[:id])
    @person.destroy

    respond_to do |format|
      format.html { redirect_to(people_url) }
      format.xml  { head :ok }
    end
  end
end

hw3/app/helpers/application_helper.rb
module ApplicationHelper
end

hw3/app/helpers/people_helper.rb
module PeopleHelper
end

hw3/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workshop Registration</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

hw3/app/views/people/_form.html.erb
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Name %><br />
    <%= f.text_field :Name %>
  </div>
  <div class="field">
    <%= f.label :Affiliation %><br />
    <%= f.text_field :Affiliation %>
  </div>
  <div class="field">
    <%= f.label :Email_Address %><br />
    <%= f.text_field :Email_Address %>
  </div>
  <div class="field">
    <%= f.label :Nickname %><br />
    <%= f.text_field :Nickname %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

hw3/app/views/people/edit.html.erb
<h1>Editing Registration</h1>

<%= render 'form' %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

hw3/app/views/people/index.html.erb
<h1>Listing People</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Affiliation</th>
    <th>Email Address</th>
    <th>Nickname</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @people.each do |person| %>
  <tr>
    <td><%= person.Name %></td>
    <td><%= person.Affiliation %></td>
    <td><%= person.Email_Address %></td>
    <td><%= person.Nickname %></td>
    <td><%= link_to 'Show', person %></td>
    <td><%= link_to 'Edit', edit_person_path(person) %></td>
    <td><%= link_to 'Destroy', person, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Registration', new_person_path %>

<br /><br /><br />

<a href="">Go back to the conference homepage</a>

hw3/app/views/people/new.html.erb
<h1>New Registration</h1>

<%= render 'form' %>

<%= link_to 'Back', people_path %>

hw3/app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @person.Name %>
</p>

<p>
  <b>Affiliation:</b>
  <%= @person.Affiliation %>
</p>

<p>
  <b>Email Address:</b>
  <%= @person.Email_Address %>
</p>

<p>
  <b>Nickname:</b>
  <%= @person.Nickname %>
</p>


<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>